In [4]:
import pandas as pd

def pl_to_float(num):
    if isinstance(num, float):
        return num
    return float(num.replace(",", "."))

url = "https://docs.google.com/spreadsheets/d/1Xeg_KqurQLsgOAikRfmxNsrqY1WkusTG/export?format=csv&gid=1139032638"
df = pd.read_csv(url, header=None, decimal=",").T
df.columns = df.iloc[0]

# Drop the first row (now redundant)
df = df[1:].reset_index(drop=True)
df

,Autor,Url,Gatunek,Lokalizacja,Metoda pozyskania,Masa ciała (g),Masa ciała (g) SD,Masa ciała ~30 dni (g),Masa ciała ~30 dni (g) SD,Masa serca (g),...,Długość skrzydła (cm),Długość skrzydła (cm) SD,Średnica stępu (cm),Średnica stępu (cm) SD,Sample M,Sample F,Sample,Korelacje,Notes,Data wykonania badania
0,Bhowmik i in.,"(PDF) MORPHOMETRIC MEASUREMENTS, PRODUCTIVE AN...",Jalali Pigeon,"Sylhet, Bangladesh",Reared in scavenging condition,"324,79","3,41","275,59","1,48",NaN,...,NaN,NaN,NaN,NaN,15,15,30,TAK,Maybe Jalali pigeon is urban pigeon in Banglad...,NaN
1,Hena i in.,Comparative weight assessment of some visceral...,Columba livia,"Sokoto, Nigeria",Bought on a market,"270,88","4,08",NaN,NaN,"2,95",...,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN
2,Celik,Morphological Characteristics of Angut Pigeons...,Columba livia domestica,"Şanlıurfa, Turkey",Breed,"361,47","1,74",NaN,NaN,NaN,...,"29,26","0,1","3,737","0,15",72,74,146,TAK,Might be reporting coef of variance instead of...,NaN
3,Agbolsu i in. (REMOVE),Carcass Characteristics of Domestic Pigeon (Co...,Columba livia domestica,NaN,NaN,"280,3","6,01",NaN,NaN,"3,43",...,NaN,NaN,NaN,NaN,NaN,NaN,30,NaN,NaN,NaN
4,Gao i in. (REMOVE),NaN,NaN,NaN,NaN,NaN,NaN,?,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Casanova,Asymmetries in captured urban rock pigeons Col...,Columba livia domestica,"Catalunya, Spain",Collected by two companies dedicated\nto pest ...,NaN,NaN,NaN,NaN,NaN,...,"22,63","1,1168","0,44","0,031",NaN,NaN,42,TAK,Where left and righ using right,NaN
6,Hetmanski 2008,(PDF) Plumage polymorphism and breeding parame...,NaN,"Gdansk, Poland",Counted at foraging sites in the autumn and wi...,389,35,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,53,58,111,NIE,Combined from genders and plummage patterns,NaN
7,Hetmanski 2011,EBOOK-Roznice-morfologiczne-i-behawioralne-mie...,NaN,"Slupsk, Poland",Extremally complicated,"381,4","29,44",NaN,NaN,NaN,...,"23,15","0,7",NaN,NaN,24,24,48,TAK,Data from combinig both genders,NaN
8,Abubakar i in.,Body weight and Morphometric traits characteri...,Nigeria Homing \r\nPigeons (Columbia livia),Ilorin (Nigeria),Bought on a market,"263,51","36,91",NaN,NaN,NaN,...,"13,68","2,07",NaN,NaN,NaN,NaN,37,NaN,NaN,NaN
9,Abubakar i in. (2),NaN,NaN,Birnin Kebbi (Nigeria),Bought on a market,"249,76","31,85",NaN,NaN,NaN,...,"12,49","1,91",NaN,NaN,NaN,NaN,51,NaN,NaN,NaN
10,Abubakar i in. (3),NaN,NaN,Osogbo (Nigeria),Bought on a market,"204,15","45,47",NaN,NaN,NaN,...,"12,4","1,39",NaN,NaN,NaN,NaN,51,NaN,NaN,NaN
11,M. N. H. Parvez i in.,https://www.banglajol.info/index.php/BJVM/arti...,"Pigeon, multiple subspieces found in Bangladesh","northern Bangladesh (Rajshahi, Natore and Pabn...",NaN,"428,25",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,300,NaN,NaN,Czerwiec -2015 do 2016

In [5]:
df["Masa ciała (g)"].dropna().apply(pl_to_float).mean(),df["Masa ciała (g)"].dropna().apply(pl_to_float).std()

(np.float64(315.351), np.float64(72.50322605083015))

In [6]:
import numpy as np

filter = df["Masa ciała (g)"].notna()

groups = np.array(
    [
        df["Sample"][filter].apply(pl_to_float).to_numpy(),
        df["Masa ciała (g)"].dropna().apply(pl_to_float).to_numpy(),
        df["Masa ciała (g) SD"].dropna().apply(pl_to_float).to_numpy(),
    ]
)

groups = [tuple(x) for x in groups.T[:-1]]
groups

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
data_cols = [
    "Masa ciała (g)",
    "Masa ciała ~30 dni (g)",
    "Masa serca (g)",
    "Masa wątroby (g)",
    "Długość ciała (cm)",
    "Rozpiętość skrzydeł (cm)",
    "Długość głowy (cm)",
    "Długość ogona (cm)",
    "Obwód klatki (cm)",
    "Długość skrzydła (cm)",
    "Średnica stępu (cm)",
]